language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"

# command to install dependencies
#install:
#  - "pip install . --use-mirrors"
#  - "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: 
  - test src/tests/unittest_commandline.py
  - test src/tests/unittest_pydoc.py
  - test src/unittest_rendering.py
